<?php

/**
 * @file
 * Install, update and uninstall functions for the commerce_pos module.
 */

/**
 * Implements hook_install.
 */
function commerce_pos_install() {
  $entity = $this->entityTypeManager->getStorage('entity_form_display')->load('commerce_product_variation.default.default');

  dpm($entity);

  //$entity->setComponent('yourfieldname', ['propertyyourechanging' => 'itsnewvalue']);
}
